GET http://localhost:3001/api/notes/ HTTP/1.1
###
GET http://localhost:3001/api/notes/3 HTTP/1.1
###
DELETE http://localhost:3001/api/notes/6233a127e2973defd689e76f HTTP/1.1
###
POST http://localhost:3001/api/notes/ HTTP/1.1
Content-Type: application/json

{
    "userId":"62339fade2973defd689e76b",
    "title":"bueno,ahora?",
    "body":"ahora, se pregunta el desarrolldor, que are!?"
}
###
PUT http://localhost:3001/api/notes/620a7bee815c37e14c8b57f9 HTTP/1.1
Content-Type: application/json

{
    "userId":3,
    "title":"que tal, te fue...",
    "body":"esto seguro que funca asi!"
}
###
POST http://localhost:3001/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username":"jonasdev.es",
    "name":"jonathan",
    "password":"jonaspassword"
}
###
GET http://localhost:3001/api/users/ HTTP/1.1